import os
try:
    os.remove("auto.gdml")
except:
    print("")
f = open("auto.gdml", "a")

f.write("""<?xml version="1.0" encoding="UTF-8" standalone="no" ?>\n""")
f.write("""<gdml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n""")
f.write("""  xsi:noNamespaceSchemaLocation="http://service-spi.web.cern.ch/service-spi/app/releases/GDML/schema/gdml.xsd">\n""")
f.write("\n")
f.write("""  <define>\n""")
f.write("""    <quantity name="worldR" type="length" value="1.2" unit="m" />\n""")
f.write("""    <quantity name="cavityS" type="length" value="1" unit="m" />\n""")
f.write("""    <quantity name="shieldS" type="length" value="1" unit="m" />\n""")
f.write("""    <quantity name="geR" type="length" value="35." unit="cm" />\n""")
f.write("""    <quantity name="geH" type="length" value="40." unit="mm" />\n""")
f.write("""    <quantity name="collimator_radius" type="length" value="100.0" unit="mm"/>\n""")
f.write("""    <quantity name="collimator_radius2" type="length" value="100.0" unit="mm"/>\n""")
f.write("""    <quantity name="collimator_innerradius" type="length" value="2" unit="mm"/>\n""")
f.write("""    <quantity name="collimator_innerradius2" type="length" value="2" unit="mm"/>\n""")
f.write("""    <quantity name="collimator_height" type="length" value="200.0" unit="mm"/>\n""")
f.write("""    <position name="colPos" unit="mm" x="0" y="0" z="150" />\n""")
f.write("""    <position name="origin" x="0" y="0" z="0"/>\n""")
f.write("""    <rotation name="noRotation" z="0"/>\n""")
f.write("""  </define>\n""")
f.write("""  <materials/>\n""")
f.write("""  <solids>\n""")
f.write("""    <orb name="worldSphere" r="worldR"/>\n""")
f.write("""    <box name="shieldBox" x="shieldS" y="shieldS" z="shieldS"/>\n""")
f.write("""    <box name="cavityBox" x="cavityS" y="cavityS" z="cavityS"/>\n""")
f.write("""    <tube name="geCyl" rmax="geR" z="geH" deltaphi="2*pi"/>\n""")
f.write("""    <cone name="collimator" rmin1="collimator_innerradius" rmax1="collimator_radius" rmin2="collimator_innerradius2" rmax2="collimator_radius2" z="collimator_height" startphi="0" deltaphi="2*pi" aunit="rad"/>\n""")
f.write("""  </solids>\n""")
f.write("\n")
f.write("""  <structure>\n""")
f.write("""    <volume name="geDetector">\n""")
f.write("""      <materialref ref="G4_Ge"/>\n""")
f.write("""      <solidref ref="geCyl"/>\n""")
f.write("""    </volume>\n""")
f.write("""   <volume name="Collimator">\n""")
f.write("""     <materialref ref="G4_Pb"/>\n""")
f.write("""     <solidref ref="collimator"/>\n""")
f.write("""    </volume>\n""")
f.write("""    <volume name="cavity">\n""")
f.write("""      <materialref ref="G4_AIR"/>\n""")
f.write("""      <solidref ref="cavityBox"/>\n""")
f.write("""      <physvol>\n""")
f.write("""        <volumeref ref="geDetector"/>\n""")
f.write("""        <positionref ref="origin"/>\n""")
f.write("""        <rotationref ref="noRotation"/>\n""")
f.write("""      </physvol>\n""")
f.write("""      <physvol>\n""")
f.write("""        <volumeref ref="Collimator"/>\n""")
f.write("""        <positionref ref="colPos"/>\n""")
f.write("""        <rotationref ref="noRotation"/>\n""")
f.write("""      </physvol>\n""")
f.write("""    </volume>\n""")
f.write("""    <volume name="shield">\n""")
f.write("""      <materialref ref="G4_Pb"/>\n""")
f.write("""      <solidref ref="shieldBox"/>\n""")
f.write("""      <physvol>\n""")
f.write("""        <volumeref ref="cavity"/>\n""")
f.write("""        <positionref ref="origin"/>\n""")
f.write("""        <rotationref ref="noRotation"/>\n""")
f.write("""      </physvol>\n""")
f.write("""    </volume>\n""")
f.write("""    <volume name="world">\n""")
f.write("""      <materialref ref="G4_Galactic"/>\n""")
f.write("""      <solidref ref="worldSphere"/>\n""")
f.write("""      <physvol>\n""")
f.write("""        <volumeref ref="shield"/>\n""")
f.write("""        <positionref ref="origin"/>\n""")
f.write("""        <rotationref ref="noRotation"/>\n""")
f.write("""      </physvol>\n""")
f.write("""    </volume>\n""")
f.write("""  </structure>\n""")
f.write("""  <setup name="Default" version="1.0">\n""")
f.write("""    <world ref="world"/>\n""")
f.write("""  </setup>\n""")
f.write("""</gdml>\n""")
f.close()